#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Jengkolonline/izinn/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Jengkol_Online"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282372139631"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
Repo1="https://raw.githubusercontent.com/Jengkolonline/izinn/main/ip"
ISP=$(cat /etc/xray/isp)
NS=$(cat /etc/xray/dns)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
Namee="MyRidwan | Project | KYT TUNNEL"
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)

ssh_service=$(/etc/init.d/ssh status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
dropbear_service=$(/etc/init.d/dropbear status | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
haproxy_service=$(systemctl status haproxy | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)                               xray_service=$(systemctl status xray | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
nginx_service=$(systemctl status nginx | grep Active | awk '{print $3}' | cut -d "(" -f2 | cut -d ")" -f1)
#Status | JENGKOLONLINE
clear
# STATUS SERVICE  SSH
if [[ $ssh_service == "running" ]]; then
   status_ssh="⭕"
else
   status_ssh="${RED}❌${NC} "
fi

# // SSH Websocket Proxy
ssh_ws=$( systemctl status ws | grep Active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g' )
if [[ $ssh_ws == "running" ]]; then
    status_ws_epro="${green}⭕${NC}"
else
    status_ws_epro="${RED}❌${NC} "
fi

# STATUS SERVICE HAPROXY
if [[ $haproxy_service == "running" ]]; then
   status_haproxy="${green}⭕${NC}"
else
   status_haproxy="${RED}❌${NC} "
fi

# STATUS SERVICE XRAY
if [[ $xray_service == "running" ]]; then
   status_xray="${green}⭕${NC}"
else
   status_xray="${RED}❌${NC} "
fi

# STATUS SERVICE NGINX
if [[ $nginx_service == "running" ]]; then
   status_nginx="${green}⭕${NC}"
else
   status_nginx="${RED}❌${NC} "
fi

# STATUS SERVICE Dropbear
if [[ $dropbear_service == "running" ]]; then
   status_dropbear="${green}⭕${NC}"
else
   status_dropbear="${RED}❌${NC} "
fi
vm=$(cat /etc/vmess/.vmess.db | wc -l)
vll=$(cat /etc/vless/.vless.db | wc -l)
trr=$(cat /etc/trojan/.trojan.db | wc -l)
ssk=$(cat /etc/shadowsocks/.shadowsocks.db | wc -l)
sssh=$(cat /etc/ssh/.ssh.db | wc -l)

ttoday="$(vnstat | grep today | awk '{print $8" "substr ($9, 1, 3)}' | head -1)"
bmon="$(vnstat -m | grep `date +%G-%m` | awk '{print $8" "substr ($9, 1 ,3)}' | head -1)"

# // Exporting IP Address
export MYIP=$( curl -s https://ipinfo.io/ip/ )
Name=$(curl -sS ${Repo1}izin | grep $MYIP | awk '{print $2}')
Exp=$(curl -sS ${Repo1}izin | grep $MYIP | awk '{print $3}')
data_ip="https://raw.githubusercontent.com/Jengkolonline/izinn/main/ip"
d2=$(date -d "$date_list" +"+%s")
d1=$(date -d "$Exp" +"+%s")
dayleft=$(( ($d1 - $d2) / 86400 ))

clear
echo -e " \033[31m##########\033[33m##########\033[32m##########\033[34m##########\033[35m##########\033[36m##########\e[0m"
echo -e " \033[31m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[34m│$NC\033[33m                       JENGKOLONLINE                      $NC\033[34m│\e[0m"
echo -e " \033[33m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e "  SSH : $status_ssh   NGINX : $status_nginx   XRAY : $status_xray   HAPROXY : $status_haproxy   WS-EPRO : $status_ws_epro   DROPBEAR : $status_dropbear         $NC"
echo -e " \033[32m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[35m│$NC \033[31mSystem OS\e[0m     :   ${putih}$MODEL${NC}"
echo -e " \033[35m│$NC \033[33mServer RAM\e[0m    :   ${putih}$RAM MB $NC"
echo -e " \033[35m│$NC \033[32mUptime Server\e[0m :   ${putih}$SERONLINE${NC}"
echo -e " \033[35m│$NC \033[35mCore System\e[0m   :   ${putih}$CORE${NC}"
echo -e " \033[35m│$NC \033[34mDate\e[0m          :   ${putih}$DATEVPS${NC}"
echo -e " \033[35m│$NC \033[36mTime\e[0m          :   ${putih}$TIMEZONE${NC}"
echo -e " \033[35m│$NC \033[33mDomain\e[0m        :   ${putih}$domain${NC}"
echo -e " \033[35m│$NC \033[32mNS Domain\e[0m     :   ${putih}$NS${NC}"
echo -e " \033[35m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e "                                      SSH    = $sssh ${NC}"
echo -e "                                      VMESS  = $sssh ${NC}"
echo -e "                                      VLESS  = $sssh ${NC}"
echo -e "                                      TROJAN = $sssh ${NC}"
echo -e "                                      SS     = $sssh ${NC}"
echo -e "                                      \033[31m═\033[32m═\033[33m═\033[34m═\033[35m═\033[36m═\033[32m═\033[34m═\033[31m═\033[33m═\033[35m═\033[36m═\033[33m═\033[31m═\e[0m"
echo -e " \033[35m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[33m│$NC \033[35m[1]\e[0m ${YELL}MENU SSH&OVPN ${NC}"      \033[33m│$NC \033[35m[5]\e[0m ${YELL}MENU SHADOWSHOCK${NC}"
echo -e " \033[33m│$NC \033[31m[2]\e[0m ${YELL}MENU VMESS${NC}"          \033[33m│$NC \033[31m[6]\e[0m ${YELL}MENU UTILITY${NC}"
echo -e " \033[33m│$NC \033[34m[3]\e[0m ${YELL}MENU VLESS${NC}"          \033[33m│$NC \033[34m[7]\e[0m ${YELL}ADD NOTIF BOT${NC}"
echo -e " \033[33m│$NC \033[36m[4]\e[0m ${YELL}MENU TROJAN${NC}"         \033[33m│$NC \033[36m[8]\e[0m ${YELL}ADD BOT PANEL${NC}"
echo -e " \033[33m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e " \033[35m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[32m│$NC \033[36mIP VPS\e[0m        :  ${putih}$IPVPS${NC}"
echo -e " \033[32m│$NC \033[34mClient Name\e[0m   :  ${putih}$Name${NC}"
echo -e " \033[32m│$NC \033[33mExp Script\e[0m    :  ${putih}$dayleft Days${NC}"
echo -e " \033[32m│$NC \033[31mName Author\e[0m   :  ${putih}$Namee${NC}"
echo -e " \033[32m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e ""
read -p "   Select From Options [ 1 - 8 or x exit ] : " menu
case $menu in
1) clear ;
    ssh
    ;;
2) clear ;
    vmess
    ;;
3) clear ;
    vless
    ;;
4) clear ;
    trojan
    ;;
5) clear ;
    shadowsocks
    ;;
6) clear ;
    utility
    ;;
7) clear ;
   bot
   ;;
8) clear ;
  wget ${BOT}xolpanel.sh && chmod +x xolpanel.sh && ./xolpanel.sh
   ;;
x) clear ;
   exit
   ;;
*) clear ;
    menu
    ;;
esac
