#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/jsjsjsjsjsjsjsjsjsjsjsjs/mekmek/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/telekalian"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/no_kalian"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
UPDATE="https://abc.xcodehoster.com/"
BOT="https://raw.githubusercontent.com/myridwan/src/ipuk/"
clear
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " \e[1;971m                      MENU SSH                \e[0m"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "  ${grenbo}[1]${NC}${YELL} Create SSH OVPN Account${NC}"
echo -e "  ${grenbo}[2]${NC}${YELL} Create Trial SSH OVPN Account${NC}"
echo -e "  ${grenbo}[3]${NC}${YELL} Delete SSH OVPN Account${NC}"
echo -e "  ${grenbo}[4]${NC}${YELL} Renew SSH OVPN Account${NC}"
echo -e "  ${grenbo}[5]${NC}${YELL} Login SSH OVPN Account${NC}"
echo -e "  ${grenbo}[6]${NC}${YELL} Member SSH OVPN Account${NC}"
echo -e "  ${grenbo}[7]${NC}${YELL} Tendang Multi Login SSH OVPN Account${NC}"
echo -e ""
echo -e "  ${grenbo}[0]${NC}${YELL} Back To Menu${NC}"
echo -e ""
read -p "  Select From Options [ 1 - 8 or 0 ] : " menu
case $menu in
1) clear ;
    add-ssh
    ;;
2) clear ;
    triall-ssh
    ;;
3) clear ;
    del-ssh
    ;;
4) clear ;
    renew-ssh
    ;;
5) clear ;
    cek-ssh
    ;;
6) clear ;
    list-akun-ssh
    ;;
7) clear ;
    tendang
    ;;
0) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
