#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/Jengkolonline/izinn/main/ip"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/Jengkol_Online"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/6282372139631"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
UPDATE="https://jengkolonline.biz.id/"
BOT="https://raw.githubusercontent.com/myridwan/src/ipuk/"
UDPCORE="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
clear
echo -e " \033[31m##########\033[33m##########\033[32m##########\033[34m##########\033[35m##########\033[36m##########\e[0m"
echo -e " \033[31m╭══════════════════════════════════════════════════════════╮\e[0m"
echo -e " \033[34m│$NC\033[33m                      SIYSTEM MENU                        $NC\033[34m│\e[0m"
echo -e " \033[33m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e "  ${grenbo}[1] ${NC} ${YELL}Running System${NC}"
echo -e "  ${grenbo}[2] ${NC} ${YELL}Menu Backup ${NC}"
echo -e "  ${grenbo}[3] ${NC} ${YELL}Info Port Service${NC}"
echo -e "  ${grenbo}[4] ${NC} ${YELL}Info Load Vps ${NC}"
echo -e "  ${grenbo}[5] ${NC} ${YELL}Speedtest ${NC}"
echo -e "  ${grenbo}[6] ${NC} ${YELL}Change Domain${NC}"
echo -e "  ${grenbo}[7] ${NC} ${YELL}Change Banner ${NC}"
echo -e "  ${grenbo}[8] ${NC} ${YELL}Restart Service ${NC}"
echo -e "  ${grenbo}[9] ${NC} ${YELL}Reboot Server${NC}"
echo -e "  ${grenbo}[10] ${NC}${YELL}Auto Kill User ${NC}"
echo -e "  ${grenbo}[11] ${NC}${YELL}Auto Reboot Server ${NC}"
echo -e "  ${grenbo}[12] ${NC}${YELL}Update Script${NC}"
echo -e "  ${grenbo}[13] ${NC}${YELL}Clear All Log ${NC}"
echo -e "  ${grenbo}[14] ${NC}${YELL}Delete All Akun Exp${NC}"
echo -e "  ${grenbo}[15] ${NC}${YELL}Installer UDP ${NC}"
echo -e "  ${grenbo}[16] ${NC}${YELL}Monitor ${NC}"
echo -e "  ${grenbo}[17] ${NC}${YELL}DNS GLOBAL ${NC}"
echo -e "  ${grenbo}[18] ${NC}${YELL}INSTALL BBR TCP ${NC}"
echo -e ""
echo -e "  ${grenbo}[0] ${NC} ${YELL}Back To Menu${NC}"
echo -e " \033[33m╰══════════════════════════════════════════════════════════╯\e[0m"
echo -e " \033[31m##########\033[33m##########\033[32m##########\033[34m##########\033[35m##########\033[36m##########\e[0m"
echo -e ""
read -p "  Select From Options [ 1 - 15 or 0 back to menu ] : " menu
case $menu in
1) clear ;
    run
    ;;
2) clear ;
    get-backres
    ;;
3) clear ;
    portin
    ;;    
4) clear ;   
    gotop
    ;;
5) clear ;    
    speedtest
    ;;
6) clear ;   
    get-domain
    ;;
7) clear ; 
    nano /etc/issue.net
    ;;
8) clear ;
   seres
   ;;
9) clear ;
   reboot
   ;;
10) clear ;
   autokill
   ;;
11) clear ;
   auto-reboot
   ;;
12) clear ;
   wget ${UPDATE}update.sh && chmod +x update.sh && ./update.sh
    ;;
13) clear ;
   clearlog
   ;;
14) clear ;
   xp
   ;;
15) clear ;
   wget --load-cookies /tmp/cookies.txt ${UDPCORE} -O install-udp && rm -rf /tmp/cookies.txt && chmod +x install-udp && ./install-udp
   ;;
16) clear ;
   monitor
   ;;
17) clear ;
   wget https://raw.githubusercontent.com/Jengkolonline/nonton/main/nf.sh && chmod +x nf.sh && ./nf.sh
   ;;
18) clear ;
   wget https://raw.githubusercontent.com/Jengkoltunnel/supreme/main/tcp.sh && chmod +x tcp.sh && ./tcp.sh
   ;;
0) clear ;
   menu
   ;;
*) clear ;
    menu
    ;;
esac
