#!/bin/bash
# COLOR VALIDATION
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\033[42m"
ISP=$(cat /etc/xray/isp)
NS=$(cat /etc/xray/dns)
CITY=$(cat /etc/xray/city)
IPVPS=$(curl -s ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
Exp="LIFETIME"
Namee="MyRidwan | Project | KYT TUNNEL"
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)

Open_SSH=$(systemctl status ssh | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Dropbear=$(systemctl status dropbear | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Dropbear_Websocket=$(systemctl status dropbear | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
SSH_Websocket=$(systemctl status ws | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
OpenVPN=$(systemctl status openvpn | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Nginx_Webserver=$(systemctl status nginx | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Haproxy=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
DNS_Server=$(systemctl status server | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
DNS_Client=$(systemctl status client | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
OpenVPN_Websocket=$(systemctl status ws | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vmess_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vmess_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vmess_None_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vless_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vless_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vless_None_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Trojan_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Trojan_WS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Shadowsocks_WS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Shadowsocks_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
if [[ $Open_SSH == "running" ]]; then
    status_1="${grenbo}Online${NC}"
else
    status_1="${RED}Offline${NC}"
fi

if [[ $Dropbear == "running" ]]; then
    status_2="${grenbo}Online${NC}"
else
    status_2="${RED}Offline${NC}"
fi

if [[ $Dropbear_Websocket == "running" ]]; then
    status_3="${grenbo}Online${NC}"
else
    status_3="${RED}Offline${NC}"
fi

if [[ $SSH_Websocket == "running" ]]; then
    status_4="${grenbo}Online${NC}"
else
    status_4="${RED}Offline${NC}"
fi

if [[ $OpenVPN == "exited" ]]; then
    status_5="${grenbo}Online${NC}"
else
    status_5="${RED}Offline${NC}"
fi

if [[ $Nginx_Webserver == "running" ]]; then
    status_6="${grenbo}Online${NC}"
else
    status_6="${RED}Offline${NC}"
fi

if [[ $Haproxy == "running" ]]; then
    status_7="${grenbo}Online${NC}"
else
    status_7="${RED}Offline${NC}"
fi

if [[ $DNS_Server == "running" ]]; then
    status_8="${grenbo}Online${NC}"
else
    status_8="${RED}Offline${NC}"
fi

if [[ $DNS_Client == "running" ]]; then
    status_9="${grenbo}Online${NC}"
else
    status_9="${RED}Offline${NC}"
fi

if [[ $OpenVPN_Websocket == "running" ]]; then
    status_10="${grenbo}Online${NC}"
else
    status_10="${RED}Offline${NC}"
fi

if [[ $XRAY_Vmess_TLS == "running" ]]; then
    status_11="${grenbo}Online${NC}"
else
    status_11="${RED}Offline${NC}"
fi

if [[ $XRAY_Vmess_gRPC == "running" ]]; then
    status_12="${grenbo}Online${NC}"
else
    status_12="${RED}Offline${NC}"
fi

if [[ $XRAY_Vmess_None_TLS == "running" ]]; then
    status_13="${grenbo}Online${NC}"
else
    status_13="${RED}Offline${NC}"
fi

if [[ $XRAY_Vless_TLS == "running" ]]; then
    status_14="${grenbo}Online${NC}"
else
    status_14="${RED}Offline${NC}"
fi

if [[ $XRAY_Vless_gRPC == "running" ]]; then
    status_15="${grenbo}Online${NC}"
else
    status_15="${RED}Offline${NC}"
fi

if [[ $XRAY_Vless_None_TLS == "running" ]]; then
    status_16="${grenbo}Online${NC}"
else
    status_16="${RED}Offline${NC}"
fi

if [[ $Trojan_gRPC == "running" ]]; then
    status_17="${grenbo}Online${NC}"
else
    status_17="${RED}Offline${NC}"
fi

if [[ $Trojan_WS == "running" ]]; then
    status_18="${grenbo}Online${NC}"
else
    status_18="${RED}Offline${NC}"
fi

if [[ $Shadowsocks_WS == "running" ]]; then
    status_19="${grenbo}Online${NC}"
else
    status_19="${RED}Offline${NC}"
fi

if [[ $Shadowsocks_gRPC == "running" ]]; then
    status_20="${grenbo}Online${NC}"
else
    status_20="${RED}Offline${NC}"
fi

# // Exporting IP Address
export MYIP=$( curl -s https://ipinfo.io/ip/ )
Name=$(curl -sS ${Repo1}izin | grep $MYIP | awk '{print $2}')
Exp=$(curl -sS ${Repo1}izin | grep $MYIP | awk '{print $3}')

ttoday="$(vnstat | grep today | awk '{print $8" "substr ($9, 1, 3)}' | head -1)"
bmon="$(vnstat -m | grep `date +%G-%m` | awk '{print $8" "substr ($9, 1 ,3)}' | head -1)"
clear
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "\e[1;97m                    INFORMATION                \e[0m"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
echo -e "   ${YELL}System OS${NC}     :   ${putih}$MODEL${NC}"
echo -e "   ${YELL}Server RAM${NC}    :   ${putih}$RAM MB $NC"
echo -e "   ${YELL}Uptime Server${NC} :   ${putih}$SERONLINE${NC}"
echo -e "   ${YELL}Core System${NC}   :   ${putih}$CORE${NC}"
echo -e "   ${YELL}Date${NC}          :   ${putih}$DATEVPS${NC}"
echo -e "   ${YELL}Time${NC}          :   ${putih}$TIMEZONE${NC}"
echo -e "   ${YELL}Domain${NC}        :   ${putih}$domain${NC}"
echo -e "   ${YELL}NS Domain${NC}     :   ${putih}$NS${NC}"
echo -e ""
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "\e[1;97m                   SERVICE RUNNING              \e[0m"
echo -e "\033[96m    ╔═════════════════════════════════════════════╗ ${NC}"
echo -e "\033[96m    ║    ${YELL}OpenSSH$NC          $NC: $grenbo$status_1${NC}                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Dropbear$NC         $NC: $grenbo$status_2                \033[96m║"
echo -e "\033[96m    ║    ${YELL}SshWS$NC            $NC: $grenbo$status_4                \033[96m║"
echo -e "\033[96m    ║    ${YELL}OpenVPN$NC          $NC: $grenbo$status_5                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Nginx$NC            $NC: $grenbo$status_6                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Haproxy$NC          $NC: $grenbo$status_7                \033[96m║"
echo -e "\033[96m    ║    ${YELL}SlowDNS$NC          $NC: $grenbo$status_8                \033[96m║"
echo -e "\033[96m    ║    ${YELL}OpenVPN$NC          $NC: $grenbo$status_10                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Vmess$NC            $NC: $grenbo$status_13                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Vless$NC            $NC: $grenbo$status_16                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Trojan$NC           $NC: $grenbo$status_18                \033[96m║"
echo -e "\033[96m    ║    ${YELL}Shadowsocks$NC      $NC: $grenbo$status_19                \033[96m║"
echo -e "\033[96m    ╚═════════════════════════════════════════════╝ ${NC}"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e " [ ${YELL}TODAY ${NC}: $grenbo$ttoday ${NC}]         ${NC}[ ${YELL}MONTH ${NC}: $grenbo$bmon ${NC}]"
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
echo -e ""
echo -e "         ${YELL}IP VPS${NC}        :  ${putih}$IPVPS${NC}"
echo -e "         ${YELL}Client Name${NC}   :  ${putih}$Name${NC}"
echo -e "         ${YELL}Exp Script${NC}    :  ${putih}$Exp${NC}"
echo -e "         ${YELL}Name Author${NC}   :  ${putih}$Namee${NC}"
echo -e ""
echo -e "\033[96m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e ""
echo -e ""
echo -e "         To access use >> \033[1;96m menu  ${NC}<< command"
echo -e ""