#!/bin/bash
clear
ipsaya=$(wget -qO- ipinfo.io/ip)
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
data_ip="https://raw.githubusercontent.com/jsjsjsjsjsjsjsjsjsjsjsjs/mekmek/main/izin"
checking_sc() {
  useexp=$(wget -qO- $data_ip | grep $ipsaya | awk '{print $3}')
  if [[ $date_list < $useexp ]]; then
    echo -ne
  else
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e "\033[42m          404 NOT FOUND AUTOSCRIPT          \033[0m"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    echo -e ""
    echo -e "            ${RED}PERMISSION DENIED !${NC}"
    echo -e "   \033[0;33mYour VPS${NC} $ipsaya \033[0;33mHas been Banned${NC}"
    echo -e "     \033[0;33mBuy access permissions for scripts${NC}"
    echo -e "             \033[0;33mContact Admin :${NC}"
    echo -e "      \033[0;36mTelegram${NC} t.me/telekalian"
    echo -e "      ${GREEN}WhatsApp${NC} wa.me/no_kalian"
    echo -e "\033[1;93m────────────────────────────────────────────\033[0m"
    exit
  fi
}
checking_sc
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
clear
grenbo="\e[92;1m"
NC='\033[0m'
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e " \e[1;97;101m               MENU VLESS               \e[0m"
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;93m  ${grenbo}1.${NC} \033[0;36mCreating Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}2.${NC} \033[0;36mTriall Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}3.${NC} \033[0;36mDetails Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}4.${NC} \033[0;36mDelete Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}5.${NC} \033[0;36mRenew Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}6.${NC} \033[0;36mLogim Vless Account${NC}"
echo -e "\033[1;93m  ${grenbo}7.${NC} \033[0;36mUsage Vless Account${NC}"
echo -e "\033[1;93m"
echo -e "\033[1;93m  ${grenbo}0.${NC} \033[0;36mBack To Menu${NC}"
echo -e ""
read -p "Select From Options [ 1 - 7 or 0 ] : " menu
case $menu in
1) clear ;
    add-vless
    ;;
2) clear ; 
    triall-vless
    ;;
3) clear ;
    user-vless
    ;;
4) clear ;
    del-vless
    ;;
5) clear ;
    renew-vless
    ;;
6) clear ;
    cek-vless
    ;;
7) clear ;
    usage-akun-xray-vless
    ;;
0) clear ;
    menu
    ;;
*) clear ;
    menu
    ;;
esac
